#!/usr/bin/env bash

COMMIT_EDITMSG="$1"

# Only display the linter output for errors.
if ! npm run linter:commit -s -- -e "$COMMIT_EDITMSG" --quiet;
then
    npm run linter:commit -s -- -e "$COMMIT_EDITMSG"
fi